In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

----------------------------------------------------------------------------------------------------

# Accidentes 2024

In [2]:
df_arrate = pd.read_csv("/Users/Arrate/Desktop/2024-Partes accidentes.xlsx - 2024-ListadoPartes.csv")
df_arrate

,NIF,Nombre,Apellido1,Apellido2,FechaParteAccidente,FechaAltaParte,Codigo,DescripcionParte,Actividad,Lugar,...,ActividadPersonal,ActividadOrganizada,Festivo,NResponsables,TamañoGrupo,CentroHospitalizacion,DescripcionGrado,Pais,Provincia,TipoAccidente
0,05277296S,MARIA,NAZAR,ENRIQUEZ DE SALAMANCA,1/1/24 0:00,1/2/24 12:04,745025061,Caida esquiando,Esquí Alpino,Baqueira Beret,...,True,False,False,0,0,NaN,Leve,España,LLEIDA,Tropiezos (caída al mismo nivel)
1,50775542Y,PABLO,SAN JOSE,PEÑA,1/1/24 14:00,1/2/24 10:48,745024991,"Montando en mtb, mi pie salio del pedal y se g...",BTT,El Pardo,...,False,False,False,1,0,NaN,NaN,España,MADRID,Otro: Golpe en el pie
2,11851622K,PAULA,ARQUERO,CONTRERAS,1/2/24 17:00,1/18/24 9:27,745038371,Caída al ir andando con la bicicleta y tropeza...,BTT,Carretera de la republica - Dehesas de Cercedilla,...,True,False,False,0,0,NaN,Leve,España,MADRID,Tropiezos (caída al mismo nivel)
3,50208024J,MIGUEL,PEREZ,PANIAGUA,1/4/24 0:00,1/15/24 16:09,745034561,Caída de manos. Golpe en la mano derecha,Carreras por montaña,La pedriza,...,False,False,False,1,1,NaN,Leve,España,MADRID,Colisión con rocas
4,09141804V,VICTOR,MORALEDA,ALVAREZ,1/4/24 19:30,1/4/24 23:32,745025901,"Accidente en rocódromo,haciendo dry tooling, c...",Rocódromo,Rocódromo indoorwall,...,False,False,False,1,9,NaN,NaN,España,MADRID,Otro: Corte con el filo del crampón
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
626,50869317X,DIEGO,MARTINEZ,CARULLA,12/24/24 13:00,12/30/24 11:34,745371711,Escalando noto un ruido muy fuerte en un dedo ...,Rocódromo,sharmaclimbing,...,False,False,False,1,1,NaN,Leve,España,MADRID,Problemas físicos
627,53766505A,JAVIER,LOPEZ,GARCIA,12/26/24 14:15,12/26/24 17:59,745371250,"Practicando escalada deportiva, se ha desprend...",Escalada en escuela,Torrent d Avall,...,True,False,False,0,3,NaN,Grave,España,ILLES BALEARS,Colisión con rocas
628,53498177Q,VIRGINIA,SANCHEZ,SALMERON,12/28/24 15:00,12/29/24 10:18,745371881,Tropiezo torciéndome el tobillo izquierdo,Carreras por montaña,Abantos,...,False,False,False,2,2,NaN,Leve,España,MADRID,Tropiezos (caída al mismo nivel)
629,70075086C,BORJA,VICENTE,ZAZO,12/29/24 17:00,3/2/25 17:55,745372611,Luxación de hombro,Escalada alta montaña,Murcia,...,True,False,False,0,0,Cieza,Leve,España,MADRID,Problemas físicos
630,71736397H,MARCOS,GONZALEZ,FERNANDEZ,12/30/24 13:10,12/31/24 9:34,745372681,Caída escalando en escuela de escalada de Fuen...,Escalada en escuela,Fuentidueña,...,True,False,False,3,3,NaN,Grave,España,SEGOVIA,Caída en vertical

In [3]:
df_arrate["NIF"] = df_arrate["NIF"].astype(str).str.strip().str.upper()

In [4]:
df_arrate["NIF"].value_counts(dropna=False)

NIF
70071185Y    3
05714595S    3
51446295X    3
78889989N    2
50942493T    2
            ..
50869317X    1
53766505A    1
53498177Q    1
70075086C    1
05277296S    1
Name: count, Length: 589, dtype: int64

In [5]:
df_arrate.isnull().sum()

NIF                        0
Nombre                     0
Apellido1                  0
Apellido2                  1
FechaParteAccidente        0
FechaAltaParte             0
Codigo                     0
DescripcionParte           0
Actividad                  0
Lugar                      0
FechaRecepcion             0
CentroUrgencias          374
Helicoptero              631
MacizoMontañoso            3
NombreParaje               3
Entrenamiento              0
ActividadPersonal          0
ActividadOrganizada        0
Festivo                    0
NResponsables              0
TamañoGrupo                0
CentroHospitalizacion    577
DescripcionGrado          42
Pais                       0
Provincia                  0
TipoAccidente              0
dtype: int64

In [6]:
df_arrate['accidentes_2024'] = df_arrate['DescripcionParte'].notna()

In [7]:
df_arrate.columns

Index(['NIF', 'Nombre', 'Apellido1', 'Apellido2', 'FechaParteAccidente',
       'FechaAltaParte', 'Codigo', 'DescripcionParte', 'Actividad', 'Lugar',
       'FechaRecepcion', 'CentroUrgencias', 'Helicoptero', 'MacizoMontañoso',
       'NombreParaje', 'Entrenamiento', 'ActividadPersonal',
       'ActividadOrganizada', 'Festivo', 'NResponsables', 'TamañoGrupo',
       'CentroHospitalizacion', 'DescripcionGrado', 'Pais', 'Provincia',
       'TipoAccidente', 'accidentes_2024'],
      dtype='object')

In [8]:
df_arrate["accidentes_2024"]

0      True
1      True
2      True
3      True
4      True
       ...
626    True
627    True
628    True
629    True
630    True
Name: accidentes_2024, Length: 631, dtype: bool

In [9]:
df_arrate[df_arrate.duplicated(subset=['NIF'], keep=False)].sort_values(by='NIF')

,NIF,Nombre,Apellido1,Apellido2,FechaParteAccidente,FechaAltaParte,Codigo,DescripcionParte,Actividad,Lugar,...,ActividadOrganizada,Festivo,NResponsables,TamañoGrupo,CentroHospitalizacion,DescripcionGrado,Pais,Provincia,TipoAccidente,accidentes_2024
359,00398302B,JOSE LUIS,GARCIA,FERNANDEZ,7/6/24 12:15,7/12/24 9:31,745229101,Según información redundante de la Organizació...,Carreras por montaña,Somiedo,...,True,False,0,0,NaN,Mortal,España,ASTURIAS,Enriscamiento,True
196,00398302B,JOSE LUIS,GARCIA,FERNANDEZ,4/11/24 19:00,4/14/24 11:50,745140301,"Tropezón y caída bajando por un sendero,fuerte...",Carreras por montaña,"Fonda Real, Navacerrada",...,False,False,1,0,NaN,Leve,España,MADRID,Tropiezos (caída al mismo nivel),True
350,00683428Y,YOLANDA,RUEDA,TANARRO,6/30/24 17:00,7/2/24 17:12,745225231,**** Resbalón y caida.apoyando mano derecha --...,Montañismo/Progresión por terreno abrupto,Pirineos,...,True,False,2,10,NaN,Leve,España,MADRID,Tropiezos (caída al mismo nivel),True
545,00683428Y,YOLANDA,RUEDA,TANARRO,11/3/24 0:00,11/18/24 12:49,745329981,Subiendo por un camino resbale y caí haciéndom...,Montañismo/Progresión por terreno abrupto,Pirineos,...,True,False,2,10,NaN,Leve,España,MADRID,Tropiezos (caída al mismo nivel),True
479,02282680E,JUAN,CAMPOS,ORTEGA,9/27/24 21:00,9/28/24 9:56,745271951,Dolor inteso en gemelo izquierdo con chasquido,Carreras por montaña,Torrelodones,...,False,False,1,1,NaN,Leve,España,MADRID,Problemas físicos,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,76249980N,JOSE RAUL,CALERO,ALVAREZ,7/31/24 20:00,8/5/24 11:16,745242021,Estábamos haciendo la ruta de la sima Berger e...,Espeleología,Berger,...,False,False,1,4,NaN,Leve,Francia,-,Problemas físicos,True
212,78889989N,MIKEL,ANTIA,ALVAREZ-ELICEGUI,4/16/24 19:45,4/17/24 8:43,745144331,entrenando en el rocódromo me siento patada en...,Rocódromo,San Sebastian de los Reyes,...,False,False,0,0,NaN,Leve,España,MADRID,Problemas físicos,True
93,78889989N,MIKEL,ANTIA,ALVAREZ-ELICEGUI,2/22/24 20:00,2/26/24 10:22,745084631,*** Torcedura con chasquido en dedo anular izq...,Rocódromo,Madrid,...,False,False,1,0,NaN,Leve,España,MADRID,Problemas físicos,True
316,X9133548H,MARIAN,PAVEL,.,6/15/24 10:30,6/17/24 20:12,745214911,Esguince tobillo al pisar mal.,Rocódromo,Roc30,...,False,False,0,0,NaN,Leve,España,MADRID,Tropiezos (caída al mismo nivel),True
567,X9133548H,MARIAN,PAVEL,.,11/17/24 14:30,11/18/24 17:11,745330391,Lesión dedo corazón mano izquierda.,Escalada en escuela,cuenca,...,False,False,1,2,NaN,Leve,España,CUENCA,Problemas físicos,True

In [10]:
df_arrate.drop_duplicates(subset=['NIF','Apellido1','Apellido2','FechaParteAccidente'], keep='first', inplace=True)

In [11]:
df_arrate[df_arrate.duplicated(subset=['NIF'], keep=False)].sort_values(by='NIF')

,NIF,Nombre,Apellido1,Apellido2,FechaParteAccidente,FechaAltaParte,Codigo,DescripcionParte,Actividad,Lugar,...,ActividadOrganizada,Festivo,NResponsables,TamañoGrupo,CentroHospitalizacion,DescripcionGrado,Pais,Provincia,TipoAccidente,accidentes_2024
196,00398302B,JOSE LUIS,GARCIA,FERNANDEZ,4/11/24 19:00,4/14/24 11:50,745140301,"Tropezón y caída bajando por un sendero,fuerte...",Carreras por montaña,"Fonda Real, Navacerrada",...,False,False,1,0,NaN,Leve,España,MADRID,Tropiezos (caída al mismo nivel),True
359,00398302B,JOSE LUIS,GARCIA,FERNANDEZ,7/6/24 12:15,7/12/24 9:31,745229101,Según información redundante de la Organizació...,Carreras por montaña,Somiedo,...,True,False,0,0,NaN,Mortal,España,ASTURIAS,Enriscamiento,True
545,00683428Y,YOLANDA,RUEDA,TANARRO,11/3/24 0:00,11/18/24 12:49,745329981,Subiendo por un camino resbale y caí haciéndom...,Montañismo/Progresión por terreno abrupto,Pirineos,...,True,False,2,10,NaN,Leve,España,MADRID,Tropiezos (caída al mismo nivel),True
350,00683428Y,YOLANDA,RUEDA,TANARRO,6/30/24 17:00,7/2/24 17:12,745225231,**** Resbalón y caida.apoyando mano derecha --...,Montañismo/Progresión por terreno abrupto,Pirineos,...,True,False,2,10,NaN,Leve,España,MADRID,Tropiezos (caída al mismo nivel),True
11,02519616N,ANTONIO,DE ORBE,MENDIOLA,1/9/24 11:00,1/9/24 17:45,745028401,Torcedura de rodilla,Senderismo,Bustarviejo,...,False,False,0,0,NaN,Leve,España,MADRID,Tropiezos (caída al mismo nivel),True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,76249980N,JOSE RAUL,CALERO,ALVAREZ,10/20/24 0:00,10/20/24 16:05,745298311,Accidente escalando. Golpe fuerte en pie derecho,Escalada en escuela,Torrelodones,...,False,False,1,2,NaN,Leve,España,GUADALAJARA,Caída en vertical,True
93,78889989N,MIKEL,ANTIA,ALVAREZ-ELICEGUI,2/22/24 20:00,2/26/24 10:22,745084631,*** Torcedura con chasquido en dedo anular izq...,Rocódromo,Madrid,...,False,False,1,0,NaN,Leve,España,MADRID,Problemas físicos,True
212,78889989N,MIKEL,ANTIA,ALVAREZ-ELICEGUI,4/16/24 19:45,4/17/24 8:43,745144331,entrenando en el rocódromo me siento patada en...,Rocódromo,San Sebastian de los Reyes,...,False,False,0,0,NaN,Leve,España,MADRID,Problemas físicos,True
316,X9133548H,MARIAN,PAVEL,.,6/15/24 10:30,6/17/24 20:12,745214911,Esguince tobillo al pisar mal.,Rocódromo,Roc30,...,False,False,0,0,NaN,Leve,España,MADRID,Tropiezos (caída al mismo nivel),True
567,X9133548H,MARIAN,PAVEL,.,11/17/24 14:30,11/18/24 17:11,745330391,Lesión dedo corazón mano izquierda.,Escalada en escuela,cuenca,...,False,False,1,2,NaN,Leve,España,CUENCA,Problemas físicos,True

# LICENCIAS 2024

In [12]:
import numpy as np
import pandas as pd

In [13]:
df_fer_2024_arrate = pd.read_csv("/Users/Arrate/Desktop/Licencias_2024y2025.xlsx - Licencias_2024.csv")

C:\Users\Arrate\AppData\Local\Temp\ipykernel_4428\635204347.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_fer_2024_arrate = pd.read_csv("/Users/Arrate/Desktop/Licencias_2024y2025.xlsx - Licencias_2024.csv")

In [14]:
df_fer_2024_arrate

,Nombre,Apellido1,Apellido2,Sexo,FechaNacimiento,PoblacionDomicilio,DescripcionProvinciaDomicilio,CodigoPostalDomicilio,Unnamed: 8,Unnamed: 9,...,NSocio,DireccionDomicilio,NIFFamiliar,TipoTarjeta,Alta,Cuaderno19,Bloqueado envíos,Unnamed: 34,Envío tarjeta,Discapacidad
0,MIGUEL ANGEL,ABAD,ABAD,H,1/26/1993,GUADALAJARA,GUADALAJARA,19003,NaN,NaN,...,77005,CALLE CONSTITUCIÓN 37 4D,NaN,D,FORM,NO,NO,NaN,NO,NO
1,CRISTINA,ABAD,ARRANZ,M,3/8/1990,VALLADOLID,VALLADOLID,47300,NaN,NaN,...,71299,CARRETERA DE PESQUERA NUMERO 30,NaN,D,SERVWEB,NO,NO,NaN,NO,NO
2,LUNA,ABAD,CAMPOS,M,4/26/2013,GETAFE,MADRID,28906,NaN,NaN,...,73846,CALLE DE LA GIGANTA ANDANDONA 6 PORTAL 1 3C,NaN,P,INDIVIDUAL,SI,NO,NaN,NO,NO
3,JOSE ANTONIO,ABAD,CANDELA,H,7/30/1936,MADRID,MADRID,28028,NaN,NaN,...,58372,"AVENIDA BAVIERA NUMERO 12 PISO 6º, IZQ",NaN,P,INDIVIDUAL,SI,NO,NaN,NO,NO
4,ESTEBAN EUSEBIO,ABAD,DE MIGUEL,H,12/16/1946,MADRID,MADRID,28017,NaN,NaN,...,56522,CALLE SERVANDO BATANERO NUMERO 1,NaN,D,ENLACE,NO,NO,NaN,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18910,PILAR,ZURDO,GOMEZ,M,2/19/1979,VALDEOLMOS,MADRID,28130,NaN,NaN,...,59252,Calle CAMINO DE SERRACINES Nº8 1ºC,NaN,P,SERVWEB,NO,SI,NaN,NO,NO
18911,ANTONIO,ZURDO,MARTIN,H,9/24/1949,S. SEBASTIAN DE LOS REYES,MADRID,28702,NaN,NaN,...,38999,"CALLE DAMASO ALONSO, 26 CHALET",NaN,D,INDIVIDUAL,SI,NO,NaN,NO,NO
18912,DIEGO,ZURDO,PEREZ,H,12/30/1978,ALCALA DE HENARES,MADRID,28804,NaN,NaN,...,55899,"Calle LUGO, 7 - 5ºA",NaN,P,INDIVIDUAL,SI,NO,NaN,NO,NO
18913,LUIS ALFONSO,ZURITA,GONZALEZ,H,8/17/1982,Madrid,MADRID,28002,NaN,NaN,...,69051,Calle Clara del Rey 59,NaN,P,ENLACE,NO,NO,NaN,SI,NO
18914,MARIA ISABEL,ZURRO,FRAILE,M,7/12/1962,MADRID,MADRID,28035,NaN,NaN,...,55184,"C/ FEDERICO CARLOS SAINZ DE ROBLES, 23",NaN,D,REMESA,SI,NO,NaN,NO,NO

In [15]:
df_fer_2024_arrate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18915 entries, 0 to 18914
Data columns (total 37 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Nombre                         18915 non-null  object
 1   Apellido1                      18915 non-null  object
 2   Apellido2                      18896 non-null  object
 3   Sexo                           18915 non-null  object
 4   FechaNacimiento                18915 non-null  object
 5   PoblacionDomicilio             18915 non-null  object
 6   DescripcionProvinciaDomicilio  18915 non-null  object
 7   CodigoPostalDomicilio          18915 non-null  object
 8   Unnamed: 8                     0 non-null      float64
 9   Unnamed: 9                     0 non-null      float64
 10  Unnamed: 10                    0 non-null      float64
 11  Estado                         18915 non-null  int64
 12  FechaAltaSolicitud             18915 non-null  object
 13  NumeroClub                     18915 non-null  object
 14  DescripcionEntidad             18915 non-null  object
 15  Temporada                      18915 non-null  int64
 16  Modalidad                      18915 non-null  object
 17  Categoria                      18915 non-null  object
 18  Complementos                   5080 non-null   object
 19  ImporteComplemento             18915 non-null  int64
 20  ImporteFMM                     18915 non-null  float64
 21  ImporteSeguro                  18915 non-null  float64
 22  ImporteFederacionEsp           18915 non-null  float64
 23  ImporteDescuento               18915 non-null  int64
 24  ImporteAmpliacion              18915 non-null  float64
 25  Cuota_Socio                    18915 non-null  int64
 26  Relacion                       18915 non-null  int64
 27  NSocio                         18915 non-null  int64
 28  DireccionDomicilio             18915 non-null  object
 29  NIFFamiliar                    554 non-null    object
 30  TipoTarjeta                    18915 non-null  object
 31  Alta                           18915 non-null  object
 32  Cuaderno19                     18915 non-null  object
 33  Bloqueado envíos               18915 non-null  object
 34  Unnamed: 34                    0 non-null      float64
 35  Envío tarjeta                  18915 non-null  object
 36  Discapacidad                   18915 non-null  object
dtypes: float64(8), int64(7), object(22)
memory usage: 5.3+ MB

In [16]:
df_fer_2024_arrate.columns

Index(['Nombre', 'Apellido1', 'Apellido2', 'Sexo', 'FechaNacimiento',
       'PoblacionDomicilio', 'DescripcionProvinciaDomicilio',
       'CodigoPostalDomicilio', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Estado', 'FechaAltaSolicitud', 'NumeroClub', 'DescripcionEntidad',
       'Temporada', 'Modalidad', 'Categoria', 'Complementos',
       'ImporteComplemento', 'ImporteFMM', 'ImporteSeguro',
       'ImporteFederacionEsp', 'ImporteDescuento', 'ImporteAmpliacion',
       'Cuota_Socio', 'Relacion', 'NSocio', 'DireccionDomicilio',
       'NIFFamiliar', 'TipoTarjeta', 'Alta', 'Cuaderno19', 'Bloqueado envíos',
       'Unnamed: 34', 'Envío tarjeta', 'Discapacidad'],
      dtype='object')

columnas a borrar: 'Sexo', 'FechaAltaSolicitud', 'Temporada',  'Complementos',
       'ImporteComplemento', 'ImporteFMM', 'ImporteSeguro',
       'ImporteFederacionEsp', 'ImporteDescuento', 'ImporteAmpliacion', 'Cuota_Socio', 'NIFFamiliar',
       'Cuaderno19', 'Bloqueado envíos'

In [17]:
# A borrar ahora: ["Unnamed: 8","Unnamed: 9","Unnamed: 10","Complementos","NIFFamiliar","Unnamed: 34",'Cuaderno19', 'Bloqueado envíos'].

df_fer_2024_arrate = df_fer_2024_arrate.drop(["Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 34",'Sexo', 'FechaAltaSolicitud', 'Temporada',  'Complementos',
       'ImporteComplemento', 'ImporteFMM', 'ImporteSeguro',
       'ImporteFederacionEsp', 'ImporteDescuento', 'ImporteAmpliacion', 'Cuota_Socio', 'NIFFamiliar',
       'Cuaderno19', 'Bloqueado envíos'], axis=1)
df_fer_2024_arrate.columns = df_fer_2024_arrate.columns.str.lower()

df_fer_2024_arrate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18915 entries, 0 to 18914
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   nombre                         18915 non-null  object
 1   apellido1                      18915 non-null  object
 2   apellido2                      18896 non-null  object
 3   fechanacimiento                18915 non-null  object
 4   poblaciondomicilio             18915 non-null  object
 5   descripcionprovinciadomicilio  18915 non-null  object
 6   codigopostaldomicilio          18915 non-null  object
 7   estado                         18915 non-null  int64
 8   numeroclub                     18915 non-null  object
 9   descripcionentidad             18915 non-null  object
 10  modalidad                      18915 non-null  object
 11  categoria                      18915 non-null  object
 12  relacion                       18915 non-null  int64
 13  nsocio                         18915 non-null  int64
 14  direcciondomicilio             18915 non-null  object
 15  tipotarjeta                    18915 non-null  object
 16  alta                           18915 non-null  object
 17  envío tarjeta                  18915 non-null  object
 18  discapacidad                   18915 non-null  object
dtypes: int64(3), object(16)
memory usage: 2.7+ MB

In [18]:
# Creamos variable edad y borrar "fechanacimiento"
df_fer_2024_arrate["fechanacimiento"] = pd.to_datetime(df_fer_2024_arrate["fechanacimiento"])
df_fer_2024_arrate["edad"] = 2024 - df_fer_2024_arrate["fechanacimiento"].dt.year
df_fer_2024_arrate = df_fer_2024_arrate.drop("fechanacimiento", axis=1)
df_fer_2024_arrate.columns

Index(['nombre', 'apellido1', 'apellido2', 'poblaciondomicilio',
       'descripcionprovinciadomicilio', 'codigopostaldomicilio', 'estado',
       'numeroclub', 'descripcionentidad', 'modalidad', 'categoria',
       'relacion', 'nsocio', 'direcciondomicilio', 'tipotarjeta', 'alta',
       'envío tarjeta', 'discapacidad', 'edad'],
      dtype='object')

In [19]:
# Crear columna federadado_2024
df_fer_2024_arrate['federado_2024'] = df_fer_2024_arrate['nombre'].notna()

In [20]:
df_fer_2024_arrate.head(5)

,nombre,apellido1,apellido2,poblaciondomicilio,descripcionprovinciadomicilio,codigopostaldomicilio,estado,numeroclub,descripcionentidad,modalidad,categoria,relacion,nsocio,direcciondomicilio,tipotarjeta,alta,envío tarjeta,discapacidad,edad,federado_2024
0,MIGUEL ANGEL,ABAD,ABAD,GUADALAJARA,GUADALAJARA,19003,3,07.28.000,FMM INDIVIDUAL,C,Mayor Varón,8592,77005,CALLE CONSTITUCIÓN 37 4D,D,FORM,NO,NO,31,True
1,CRISTINA,ABAD,ARRANZ,VALLADOLID,VALLADOLID,47300,3,07.28.370,CDE TODOVERTICAL,B,Mayor Mujer,3660,71299,CARRETERA DE PESQUERA NUMERO 30,D,SERVWEB,NO,NO,34,True
2,LUNA,ABAD,CAMPOS,GETAFE,MADRID,28906,3,07.28.000,FMM INDIVIDUAL,AU,Infantil Mujer,263,73846,CALLE DE LA GIGANTA ANDANDONA 6 PORTAL 1 3C,P,INDIVIDUAL,NO,NO,11,True
3,JOSE ANTONIO,ABAD,CANDELA,MADRID,MADRID,28028,3,07.28.000,FMM INDIVIDUAL,AU,Mayor Varón,182,58372,"AVENIDA BAVIERA NUMERO 12 PISO 6º, IZQ",P,INDIVIDUAL,NO,NO,88,True
4,ESTEBAN EUSEBIO,ABAD,DE MIGUEL,MADRID,MADRID,28017,3,07.28.000,INDIVIDUAL,A,Mayor Varón,3052,56522,CALLE SERVANDO BATANERO NUMERO 1,D,ENLACE,NO,NO,78,True

In [21]:
# Renombrar algunas de las columnas _2024 (especificando el año) de cara a la unión de los dataset.

columnas = ['estado', 'numeroclub', 'descripcionentidad',
       'modalidad', 'cuota_socio', 'relacion',
       'tipotarjeta', 'alta', 'envío tarjeta',
       'edad']
df_fer_2024_arrate.rename(columns={col: col + "_2024" for col in columnas}, inplace=True)
df_fer_2024_arrate.columns

Index(['nombre', 'apellido1', 'apellido2', 'poblaciondomicilio',
       'descripcionprovinciadomicilio', 'codigopostaldomicilio', 'estado_2024',
       'numeroclub_2024', 'descripcionentidad_2024', 'modalidad_2024',
       'categoria', 'relacion_2024', 'nsocio', 'direcciondomicilio',
       'tipotarjeta_2024', 'alta_2024', 'envío tarjeta_2024', 'discapacidad',
       'edad_2024', 'federado_2024'],
      dtype='object')

In [22]:
# Borramos duplicados basados en 'nombre','apellido1','apellido2','poblaciondomicilio'
df_fer_2024_arrate.drop_duplicates(subset=['nombre','apellido1','apellido2','poblaciondomicilio'], keep='first', inplace=True)

In [23]:
df_fer_2024_arrate.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18898 entries, 0 to 18914
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   nombre                         18898 non-null  object
 1   apellido1                      18898 non-null  object
 2   apellido2                      18879 non-null  object
 3   poblaciondomicilio             18898 non-null  object
 4   descripcionprovinciadomicilio  18898 non-null  object
 5   codigopostaldomicilio          18898 non-null  object
 6   estado_2024                    18898 non-null  int64
 7   numeroclub_2024                18898 non-null  object
 8   descripcionentidad_2024        18898 non-null  object
 9   modalidad_2024                 18898 non-null  object
 10  categoria                      18898 non-null  object
 11  relacion_2024                  18898 non-null  int64
 12  nsocio                         18898 non-null  int64
 13  direcciondomicilio             18898 non-null  object
 14  tipotarjeta_2024               18898 non-null  object
 15  alta_2024                      18898 non-null  object
 16  envío tarjeta_2024             18898 non-null  object
 17  discapacidad                   18898 non-null  object
 18  edad_2024                      18898 non-null  int32
 19  federado_2024                  18898 non-null  bool
dtypes: bool(1), int32(1), int64(3), object(15)
memory usage: 2.8+ MB

 Columnas a cambiar: categoría (Niña, niño, mujer, hombre), discapacidad (si, no)

# Licencias 2025

In [25]:
df_fer_2025_arrate = pd.read_csv("/Users/Arrate/Desktop/Licencias_2025.csv")

df_fer_2025_arrate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18251 entries, 0 to 18250
Data columns (total 39 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   NIF                            18251 non-null  object
 1   Nombre                         18251 non-null  object
 2   Apellido1                      18251 non-null  object
 3   Apellido2                      18233 non-null  object
 4   Sexo                           18251 non-null  object
 5   FechaNacimiento                18251 non-null  object
 6   PoblacionDomicilio             18251 non-null  object
 7   DescripcionProvinciaDomicilio  18251 non-null  object
 8   CodigoPostalDomicilio          18251 non-null  int64
 9   Telefono1                      18251 non-null  int64
 10  Telefono2                      4667 non-null   object
 11  Email                          18247 non-null  object
 12  Estado                         18251 non-null  int64
 13  FechaAltaSolicitud             18251 non-null  object
 14  NumeroClub                     18251 non-null  object
 15  DescripcionEntidad             18251 non-null  object
 16  Temporada                      18251 non-null  int64
 17  Modalidad                      18251 non-null  object
 18  Categoria                      18251 non-null  object
 19  Complementos                   4803 non-null   object
 20  ImporteComplemento             18251 non-null  int64
 21  ImporteFMM                     18251 non-null  float64
 22  ImporteSeguro                  18251 non-null  float64
 23  ImporteFederacionEsp           18251 non-null  float64
 24  ImporteDescuento               18251 non-null  int64
 25  ImporteAmpliacion              18251 non-null  float64
 26  Cuota_Socio                    18251 non-null  int64
 27  Relacion                       18251 non-null  int64
 28  NSocio                         18251 non-null  int64
 29  DireccionDomicilio             18251 non-null  object
 30  NIFFamiliar                    509 non-null    object
 31  TipoTarjeta                    18251 non-null  object
 32  Alta                           18251 non-null  object
 33  Cuaderno19                     18251 non-null  object
 34  Bloqueado envíos               18251 non-null  object
 35  NCuentaBancaria                7622 non-null   object
 36  Acceso formulario              18251 non-null  object
 37  Envío tarjeta                  18251 non-null  object
 38  Discapacidad                   18251 non-null  object
dtypes: float64(4), int64(9), object(26)
memory usage: 5.4+ MB

In [26]:
df_fer_2025_arrate.head(5)

,NIF,Nombre,Apellido1,Apellido2,Sexo,FechaNacimiento,PoblacionDomicilio,DescripcionProvinciaDomicilio,CodigoPostalDomicilio,Telefono1,...,DireccionDomicilio,NIFFamiliar,TipoTarjeta,Alta,Cuaderno19,Bloqueado envíos,NCuentaBancaria,Acceso formulario,Envío tarjeta,Discapacidad
0,51451495N,BEATRIZ,ABAD,CARRILLO,M,3/11/1986,MADRID,MADRID,28039,615274289,...,CALLE LORENZA CORREA 23 3 DRCHA IZDA,NaN,D,ENLACE,NO,NO,NaN,https://fmmlicencias.com/FMM/AccesoFederado.as...,NO,NO
1,05305866L,EDUARDO,ABAD,DIAZ,H,10/24/1990,MADRID,MADRID,28010,679906030,...,C/ ALONSO CANO Nº 15 BAJO A,NaN,P,INDIVIDUAL,SI,NO,ES2814650200211719279500,https://fmmlicencias.com/FMM/AccesoFederado.as...,NO,NO
2,52479225X,AARON,ABAD,ESTEBAN,H,1/26/1981,LAS ROZAS,MADRID,28290,630700068,...,CALLE AMPURIAS NUMERO 12,NaN,D,REMESA,SI,NO,ES4300810469410001005211,https://fmmlicencias.com/FMM/AccesoFederado.as...,NO,NO
3,50725543D,JAIME,ABAD,ESTEBAN,H,4/12/1972,MADRID,MADRID,28002,629630182,...,Calle PADRE CLARET Numero 11 Piso 5 Letra A,NaN,P,INDIVIDUAL,SI,NO,ES8700730100560407453503,https://fmmlicencias.com/FMM/AccesoFederado.as...,NO,NO
4,00671764A,CONCEPCION,ABAD,FERNANDEZ,M,6/19/1957,MADRID,MADRID,28029,651758322,...,CALLE VILLA DE MARIN 28,NaN,P,SERVWEB,NO,NO,NaN,https://fmmlicencias.com/FMM/AccesoFederado.as...,NO,NO

In [27]:
# Borrar las mismas columnas que en licencias 2024 + especificas de 2025
df_fer_2025_arrate = df_fer_2025_arrate.drop(['Sexo', 'FechaAltaSolicitud', 'Temporada',  'Complementos',
       'ImporteComplemento', 'ImporteFMM', 'ImporteSeguro',
       'ImporteFederacionEsp', 'ImporteDescuento', 'ImporteAmpliacion',
       'Cuota_Socio', 'NIFFamiliar',
       'Cuaderno19', 'Bloqueado envíos','Telefono1',
       'Email',"NIFFamiliar", 'NCuentaBancaria', 'Telefono2', 'Acceso formulario'], axis=1)
df_fer_2025_arrate.columns = df_fer_2025_arrate.columns.str.lower()

# Creamos variable edad y borrar "fechanacimiento"
df_fer_2025_arrate["fechanacimiento"] = pd.to_datetime(df_fer_2025_arrate["fechanacimiento"])
df_fer_2025_arrate["edad"] = 2025 - df_fer_2025_arrate["fechanacimiento"].dt.year
df_fer_2025_arrate = df_fer_2025_arrate.drop("fechanacimiento", axis=1)

# Crear columna federadado_2025
df_fer_2025_arrate['federado_2025'] = df_fer_2025_arrate['nombre'].notna()

# Renombrar algunas de las columnas _2025 (especificando el año) de cara a la unión de los dataset.

columnas = ['estado', 'numeroclub', 'descripcionentidad',
       'modalidad', 'relacion',
       'tipotarjeta', 'envío tarjeta', 'alta',
       'edad']
df_fer_2025_arrate.rename(columns={col: col + "_2025" for col in columnas}, inplace=True)

In [28]:
# Borramos duplicados basados en 'nombre','apellido1','apellido2','poblaciondomicilio'
df_fer_2025_arrate.drop_duplicates(subset=['nif','nombre','apellido1','apellido2','poblaciondomicilio'], keep='first', inplace=True)

In [29]:
df_fer_2025_arrate.columns

Index(['nif', 'nombre', 'apellido1', 'apellido2', 'poblaciondomicilio',
       'descripcionprovinciadomicilio', 'codigopostaldomicilio', 'estado_2025',
       'numeroclub_2025', 'descripcionentidad_2025', 'modalidad_2025',
       'categoria', 'relacion_2025', 'nsocio', 'direcciondomicilio',
       'tipotarjeta_2025', 'alta_2025', 'envío tarjeta_2025', 'discapacidad',
       'edad_2025', 'federado_2025'],
      dtype='object')

In [30]:
df_fer_2025_arrate.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18249 entries, 0 to 18250
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   nif                            18249 non-null  object
 1   nombre                         18249 non-null  object
 2   apellido1                      18249 non-null  object
 3   apellido2                      18231 non-null  object
 4   poblaciondomicilio             18249 non-null  object
 5   descripcionprovinciadomicilio  18249 non-null  object
 6   codigopostaldomicilio          18249 non-null  int64
 7   estado_2025                    18249 non-null  int64
 8   numeroclub_2025                18249 non-null  object
 9   descripcionentidad_2025        18249 non-null  object
 10  modalidad_2025                 18249 non-null  object
 11  categoria                      18249 non-null  object
 12  relacion_2025                  18249 non-null  int64
 13  nsocio                         18249 non-null  int64
 14  direcciondomicilio             18249 non-null  object
 15  tipotarjeta_2025               18249 non-null  object
 16  alta_2025                      18249 non-null  object
 17  envío tarjeta_2025             18249 non-null  object
 18  discapacidad                   18249 non-null  object
 19  edad_2025                      18249 non-null  int32
 20  federado_2025                  18249 non-null  bool
dtypes: bool(1), int32(1), int64(4), object(15)
memory usage: 2.9+ MB

In [31]:
# Unión de los df de licencias 2024 + 2025
# .merge() --- how='outer' 
# conserva todas las filas de ambos dataframes, y las columnas comunes aparecen una sola vez.

columnas_comunes = list(set(df_fer_2024_arrate.columns) & set(df_fer_2025_arrate.columns))
df_federados = df_fer_2024_arrate.merge(df_fer_2025_arrate, on=columnas_comunes, how='outer')

In [32]:
df_federados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27208 entries, 0 to 27207
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   nombre                         27208 non-null  object
 1   apellido1                      27208 non-null  object
 2   apellido2                      27175 non-null  object
 3   poblaciondomicilio             27208 non-null  object
 4   descripcionprovinciadomicilio  27208 non-null  object
 5   codigopostaldomicilio          27208 non-null  object
 6   estado_2024                    18898 non-null  float64
 7   numeroclub_2024                18898 non-null  object
 8   descripcionentidad_2024        18898 non-null  object
 9   modalidad_2024                 18898 non-null  object
 10  categoria                      27208 non-null  object
 11  relacion_2024                  18898 non-null  float64
 12  nsocio                         27208 non-null  int64
 13  direcciondomicilio             27208 non-null  object
 14  tipotarjeta_2024               18898 non-null  object
 15  alta_2024                      18898 non-null  object
 16  envío tarjeta_2024             18898 non-null  object
 17  discapacidad                   27208 non-null  object
 18  edad_2024                      18898 non-null  float64
 19  federado_2024                  18898 non-null  object
 20  nif                            18249 non-null  object
 21  estado_2025                    18249 non-null  float64
 22  numeroclub_2025                18249 non-null  object
 23  descripcionentidad_2025        18249 non-null  object
 24  modalidad_2025                 18249 non-null  object
 25  relacion_2025                  18249 non-null  float64
 26  tipotarjeta_2025               18249 non-null  object
 27  alta_2025                      18249 non-null  object
 28  envío tarjeta_2025             18249 non-null  object
 29  edad_2025                      18249 non-null  float64
 30  federado_2025                  18249 non-null  object
dtypes: float64(6), int64(1), object(24)
memory usage: 6.4+ MB

In [33]:
df_federados.head()

,nombre,apellido1,apellido2,poblaciondomicilio,descripcionprovinciadomicilio,codigopostaldomicilio,estado_2024,numeroclub_2024,descripcionentidad_2024,modalidad_2024,...,estado_2025,numeroclub_2025,descripcionentidad_2025,modalidad_2025,relacion_2025,tipotarjeta_2025,alta_2025,envío tarjeta_2025,edad_2025,federado_2025
0,MIGUEL,VELA,BATANERO,19001,GUADALAJARA,19001,3.0,07.28.000,FMM INDIVIDUAL,B6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CAROLINA,REDONDO,CALVO,28,MADRID,28224,3.0,07.28.010,C. ALPINO PIEDRAFITA-POZUELO,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MARIA DOLORES,CRESPO,HERVAS,28002,MADRID,28002,3.0,07.28.455,C.D.E. PURA VIDA MONTAÑA Y NATURALEZA,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ANGELICA,SANZ,ULL,28002,MADRID,28002,3.0,07.28.000,FMM INDIVIDUAL,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MIGUEL,ARNES,GOMEZ,28033,MADRID,28033,3.0,07.28.000,FMM INDIVIDUAL,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Licencias 2023

In [31]:
df_fer_2023_arrate = pd.read_csv("/Users/Arrate/Desktop/2023.xlsx - 2023.csv")

df_fer_2023_arrate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19489 entries, 0 to 19488
Data columns (total 39 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   NIF                            19489 non-null  object
 1   Nombre                         19489 non-null  object
 2   Apellido1                      19489 non-null  object
 3   Apellido2                      19478 non-null  object
 4   Sexo                           19489 non-null  object
 5   FechaNacimiento                19489 non-null  object
 6   PoblacionDomicilio             19489 non-null  object
 7   DescripcionProvinciaDomicilio  19489 non-null  object
 8   CodigoPostalDomicilio          19489 non-null  object
 9   Telefono1                      19471 non-null  object
 10  Telefono2                      5363 non-null   object
 11  Email                          19480 non-null  object
 12  Estado                         19489 non-null  int64
 13  FechaAltaSolicitud             19489 non-null  object
 14  NumeroClub                     19489 non-null  object
 15  DescripcionEntidad             19489 non-null  object
 16  Temporada                      19489 non-null  int64
 17  Modalidad                      19489 non-null  object
 18  Categoria                      19489 non-null  object
 19  Complementos                   5654 non-null   object
 20  ImporteComplemento             19489 non-null  int64
 21  ImporteFMM                     19489 non-null  float64
 22  ImporteSeguro                  19489 non-null  float64
 23  ImporteFederacionEsp           19489 non-null  int64
 24  ImporteDescuento               19489 non-null  int64
 25  ImporteAmpliacion              19489 non-null  int64
 26  Cuota_Socio                    19489 non-null  int64
 27  Relacion                       19489 non-null  int64
 28  NSocio                         19489 non-null  int64
 29  DireccionDomicilio             19489 non-null  object
 30  NIFFamiliar                    561 non-null    object
 31  TipoTarjeta                    19489 non-null  object
 32  Alta                           19489 non-null  object
 33  Cuaderno19                     19489 non-null  object
 34  Bloqueado envíos               19489 non-null  object
 35  NCuentaBancaria                8661 non-null   object
 36  Acceso formulario              19489 non-null  object
 37  Envío tarjeta                  19489 non-null  object
 38  Discapacidad                   19489 non-null  object
dtypes: float64(2), int64(9), object(28)
memory usage: 5.8+ MB

C:\Users\Arrate\AppData\Local\Temp\ipykernel_3904\3567124890.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_fer_2023_arrate = pd.read_csv("/Users/Arrate/Desktop/2023.xlsx - 2023.csv")

In [ ]:
# Borrar las mismas columnas que en licencias 2024 y 2025 + especificas de 2023
df_fer_2023_arrate = df_fer_2023_arrate.drop(['Telefono1','FechaAltaSolicitud', 'Email',"Complementos","NIFFamiliar",'Cuaderno19', 'Bloqueado envíos', 'NCuentaBancaria', 'Temporada', 'Telefono2', 'Acceso formulario'], axis=1)
df_fer_2023_arrate.columns = df_fer_2023_arrate.columns.str.lower()

# Creamos variable edad y borrar "fechanacimiento"
df_fer_2023_arrate["fechanacimiento"] = pd.to_datetime(df_fer_2023_arrate["fechanacimiento"])
df_fer_2023_arrate["edad"] = 2023 - df_fer_2023_arrate["fechanacimiento"].dt.year
df_fer_2023_arrate = df_fer_2023_arrate.drop("fechanacimiento", axis=1)

# Crear columna federadado_2025
df_fer_2023_arrate['federado_2023'] = df_fer_2023_arrate['nombre'].notna()

# Renombrar algunas de las columnas _2023 (especificando el año) de cara a la unión de los dataset.

columnas = ['estado', 'numeroclub', 'descripcionentidad',
       'modalidad', 'importecomplemento', 'importefmm',
       'importeseguro', 'importefederacionesp', 'importedescuento',
       'importeampliacion', 'cuota_socio', 'relacion',
       'tipotarjeta', 'envío tarjeta', 'alta',
       'edad']
df_fer_2023_arrate.rename(columns={col: col + "_2023" for col in columnas}, inplace=True)